# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(1073, 780)
        Calculator.setStyleSheet("background-color: rgb(255, 229, 228);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Calculator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 1041, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BtnPerestanovki = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.BtnPerestanovki.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnPerestanovki.sizePolicy().hasHeightForWidth())
        self.BtnPerestanovki.setSizePolicy(sizePolicy)
        self.BtnPerestanovki.setStyleSheet("background-color: rgb(255, 166, 148);")
        self.BtnPerestanovki.setObjectName("BtnPerestanovki")
        self.horizontalLayout.addWidget(self.BtnPerestanovki)
        self.BtnRazmeshenie = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnRazmeshenie.sizePolicy().hasHeightForWidth())
        self.BtnRazmeshenie.setSizePolicy(sizePolicy)
        self.BtnRazmeshenie.setStyleSheet("background-color: rgb(255, 166, 148);")
        self.BtnRazmeshenie.setObjectName("BtnRazmeshenie")
        self.horizontalLayout.addWidget(self.BtnRazmeshenie)
        self.BtnSochetanie = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSochetanie.sizePolicy().hasHeightForWidth())
        self.BtnSochetanie.setSizePolicy(sizePolicy)
        self.BtnSochetanie.setStyleSheet("background-color: rgb(255, 166, 148);")
        self.BtnSochetanie.setObjectName("BtnSochetanie")
        self.horizontalLayout.addWidget(self.BtnSochetanie)
        self.BtnMathojidanie = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnMathojidanie.sizePolicy().hasHeightForWidth())
        self.BtnMathojidanie.setSizePolicy(sizePolicy)
        self.BtnMathojidanie.setStyleSheet("background-color: rgb(255, 166, 148);")
        self.BtnMathojidanie.setObjectName("BtnMathojidanie")
        self.horizontalLayout.addWidget(self.BtnMathojidanie)
        self.BtnDispersion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnDispersion.sizePolicy().hasHeightForWidth())
        self.BtnDispersion.setSizePolicy(sizePolicy)
        self.BtnDispersion.setStyleSheet("background-color: rgb(255, 166, 148);")
        self.BtnDispersion.setObjectName("BtnDispersion")
        self.horizontalLayout.addWidget(self.BtnDispersion)
        self.BtnOtkloneniye = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnOtkloneniye.sizePolicy().hasHeightForWidth())
        self.BtnOtkloneniye.setSizePolicy(sizePolicy)
        self.BtnOtkloneniye.setStyleSheet("background-color: rgb(255, 166, 148);")
        self.BtnOtkloneniye.setObjectName("BtnOtkloneniye")
        self.horizontalLayout.addWidget(self.BtnOtkloneniye)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Калькулятор"))
        self.BtnPerestanovki.setText(_translate("Calculator", "Число перестановок"))
        self.BtnRazmeshenie.setText(_translate("Calculator", "Число размещений"))
        self.BtnSochetanie.setText(_translate("Calculator", "Число сочетаний"))
        self.BtnMathojidanie.setText(_translate("Calculator", "Математическое\n"
"ожидание"))
        self.BtnDispersion.setText(_translate("Calculator", "Дисперсия"))
        self.BtnOtkloneniye.setText(_translate("Calculator", "Среднеквадратическое\n"
"отклонение"))
